name: flutter_form_pro_example
publish_to: "none"
description: Example app for flutter_form_pro
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_pro:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
