name: flutter_form_pro
description: "Professional, extensible form validation and widgets with Thai-first i18n."
version: 0.0.3
homepage: https://github.com/Kidpech-code/flutter_form_pro
repository: https://github.com/Kidpech-code/flutter_form_pro
issue_tracker: https://github.com/Kidpech-code/flutter_form_pro/issues
topics:
  - validation
  - forms
  - i18n
  - flutter

environment:
  sdk: ^3.8.1
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/i18n/
    - assets/images/
screenshots:
  - description: Main demo screen
    path: assets/images/screenshot.png
