name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Dart format check
        run: dart format --output=none --set-exit-if-changed .
      - name: Fetch packages (root)
        run: flutter pub get
      - name: Analyze (root)
        run: flutter analyze
      - name: Run tests (root)
        run: flutter test
      - name: Analyze example app
        run: |
          cd example
          flutter pub get
          flutter analyze
